rich_progress_bar:
  _target_: pytorch_lightning.callbacks.RichProgressBar
  refresh_rate: 1
  leave: True
  theme:
    description: "green_yellow"
    progress_bar: "green1"
    progress_bar_finished: "green1"
    progress_bar_pulse: "green1"
    batch_progress: "green_yellow"
    time: "grey82"
    processing_speed: "grey82"
    metrics: "grey82"