_target_: pytorch_lightning.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1
max_epochs: 1

accelerator: cpu
devices: 1

# mixed precision for extra speed-up
#precision: 16

# perform a validation loop every N training epochs
#val_check_interval: 1.0
log_every_n_steps: 5


# set True to to ensure deterministic results
# makes training slower but gives more reproducibility
deterministic: False